### ISSUE TITLE
this wont ever work

### ISSUE THREAD

**Issue by 7431** [PlutoSolutions/lualoader#4]
this loader isnt gonna work for a couple reasons:

1. the LuaClassLoader isnt a sub-classloader of `Launch.classLoader` so all of your client classes are gonna be running on a different classloader context which is gonna fuck with a lot of stuff. 
https://github.com/PlutoSolutions/lualoader/blob/d8faf2ba998b8561543a11e3a4b2154eb55a5a0a/src/main/java/mephedronesolutions/lualoader/classloader/LuaClassLoader.java#L19

2. the loader doesnt address circularity errors: given a class `A` and a class `B` inside ur client, if `class B extends A` and class `B` gets downloaded/loaded first, then the loader will throw a `ClassNotFoundException` for class `A`.

3. if ur mixins have references to classes from ur client then spongepowered isnt gonna be able to find the bytecode for them. theres a solution for this but it would take a while to explain.

3. this doesnt really count as a reason that it wont work but keeping mixins in the loader is kind of a bad idea. if u load ur mixins properly u can do it in a few ways that makes them hard to dump. so ur kind of losing the leverage against anyone who is trying to crack.

still better than falcon lol.

**Comment by fuckyouthinkimboogieman** [comment]
>the LuaClassLoader isnt a sub-classloader of Launch.classLoader so all of your client classes are gonna be running on a different classloader context which is gonna fuck with a lot of stuff.

luaclassloader overrides findclass. as you can see in lualoader class we load all the classes through luaclassloader.
lua class loader overrides findclass, if it contains class with name like in arg, it will return this class

>the loader doesnt address circularity errors: given a class A and a class B inside ur client, if class B extends A and class B gets downloaded/loaded first, then the loader will throw a ClassNotFoundException for class A

as you can see, there is an entrypoint, which means that classes are getting loaded before everything, before initialization of client and stuff, so there is no way that it will throw classnotfoundexception

>if ur mixins have references to classes from ur client then spongepowered isnt gonna be able to find the bytecode for them. theres a solution for this but it would take a while to explain.

^

>this doesnt really count as a reason that it wont work but keeping mixins in the loader is kind of a bad idea. if u load ur mixins properly u can do it in a few ways that makes them hard to dump. so ur kind of losing the leverage against anyone who is trying to crack.

mixins are in client jar, they are getting loaded same as all the other classes, and after they are loaded, we initalize mixin bootstrap

**Comment by fuckyouthinkimboogieman** [comment]
about luaclassloader: when classes are required, it does loadClass(String name) which requires findClass(String name), and we are overriding this function

**Comment by fuckyouthinkimboogieman** [comment]
oh wait bruh yea mixins are in package of loader but anyways its very easy to change

**Comment by fuckyouthinkimboogieman** [comment]
just move package mixins to client directory

**Comment by 7431** [comment]
for the first thing basically just look up on google "java classloader context" for a better explanation than anything i could say. classes are different across classloaders, so for example if you reference Minecraft.class from a classloader context that isn't Launch.classLoader then a new instance of Minecraft.class is gonna be created, so the static block will run twice and will essentially fuck up everything.

^ u can fix this by doing super(Launch.classLoader); in the constructor of LuaClassLoader

ok about the circularity thing cuz maybe i wasn't being clear: let's say u have a class AutoCrystal that extends Module. When the client is downloading classes, if it comes across AutoCrystal before Module (which will happen at some point), java will try to define AutoCrystal and in turn will search for Module. this will call loadClass, and since ur classloader's loadClass method doesn't account for classes that haven't been downloaded yet, u will get a ClassNotFound for Module.

^ u can fix this by downloading the bytes first,saving them, then defining them all, and having loadClass dynamically define the class being searched for by parsing the saved bytes.

mixin thing: spongepowered needs the raw bytecode of the mixin classes in order to work. so u did the easy way which was to put the mixins in the loader which is fine. the issue is that spongepowered also needs the bytecode of any classes that your mixins reference. so for example if u have ur own EventBus and you call EventBus.post(event) in some mixin, spongepowered needs the bytes of the EventBus class or the mixin will fail to load. if your EventBus class is dynamically loaded, it has no way to get the bytes and ur game will crash.

^ there's no easy way to fix this. i have a method for my loader but it's complicated and i would rather not share it anyway.

i would commit these fixes if i had time but i don't so

**Comment by fuckyouthinkimboogieman** [comment]
> for the first thing basically just look up on google "java classloader context" for a better explanation than anything i could say. classes are different across classloaders, so for example if you reference Minecraft.class from a classloader context that isn't Launch.classLoader then a new instance of Minecraft.class is gonna be created, so the static block will run twice and will essentially fuck up everything.

okay

> u can fix this by downloading the bytes first,saving them, then defining them all, and having loadClass dynamically define the class being searched for by parsing the saved bytes.

thats how its realised right now lol

> mixin thing: spongepowered needs the raw bytecode of the mixin classes in order to work. so u did the easy way which was to put the mixins in the loader which is fine. the issue is that spongepowered also needs the bytecode of any classes that your mixins reference. so for example if u have ur own EventBus and you call EventBus.post(event) in some mixin, spongepowered needs the bytes of the EventBus class or the mixin will fail to load. if your EventBus class is dynamically loaded, it has no way to get the bytes and ur game will crash.

mixins aren't getting initialized before all the classes are getting downloaded

**Comment by fuckyouthinkimboogieman** [comment]
and who are you actually
can you please message me in discord or telegram
yoursleep#1834
@encorporated
